### ISSUE TITLE
DSLs in resources

### ISSUE THREAD

**Issue by bsbodden** [caponetto/awesome-template#1]
Thanks for the archetype template! Time saver for sure. I've been able to use this with most resources (DRLs, Enums, Models) except for DSL definitions. Add any DSL file to `archetype-resources` and you get:

```
The archetype could not be added.
Error details: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: Error merging velocity templates: Unable to find resource 'archetype-resources/src/main/resources/myDsl.dsl'
```

**Comment by caponetto** [comment]
Hi @bsbodden! Thanks for using this code.
I am not able to reproduce this error, could you please share more details, such as OS version, maven version, BC version, the file structure of your custom archetype?

**Comment by bsbodden** [comment]
Thanks for the reply @caponetto. Here's what I have. I've tried this on two different environments. 

## Environment #1 - Mac, Java 11, Maven 3.6.0

```
$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /Users/bsb/.sdkman/candidates/maven/current
Java version: 11.0.1, vendor: Azul Systems, Inc., runtime: /Users/bsb/.sdkman/candidates/java/11.0.1-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"
```

I added the properties for the mvn compile plugin set to 11:

```
  <properties>
	<maven.compile.source>11</maven.compile.source>
	<maven.compiler.target>11</maven.compiler.target>
  </properties>
```

The archetype installs fine with the sample resources you provided. But, If I add a simple DSL template like `MyDSL.dsl`:

```
[then]Say "{message}"=System.out.println("{message}");
```

I get:

<img width="620" alt="mvn-arch" src="https://user-images.githubusercontent.com/24109/85031143-2aef5d80-b133-11ea-87b5-d169adea5fc5.png">

The other environment is:


## Environment #2 - Ubuntu, Java 11, Maven 3.6.3

```
 $ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/bsambodd/installs/apache-maven-3.6.3
Java version: 11.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-957.21.2.el7.x86_64", arch: "amd64", family: "unix"
```
The GAV I'm using on this system is different and the DSL is called `Results.dsl`:

![archetype-install-issue](https://user-images.githubusercontent.com/24109/85032752-300dd600-b14e-11ea-9e27-3ae0509e8558.PNG)

*Note* On the Mac I get a more generic error, on Linux the actual DSL file is mentioned in the error. Don't know if that is a clue.

**Comment by bsbodden** [comment]
Update. Removing:
```
  <properties>
	<maven.compile.source>11</maven.compile.source>
	<maven.compiler.target>11</maven.compiler.target>
  </properties>
```
Fixes it!

**Comment by caponetto** [comment]
Cool! I'm glad it worked.

**Comment by bsbodden** [comment]
@caponetto Sorry, I spoke too soon. Unfortunately that fixed it only on the Mac. Tried the same on the Linux and got the error on the screenshot. I used this project without modifications, build on both instaledl and it all works. Added the Eclipse generated DSL to both, I can install the Archetype build/installed on the Mac but not the one on Linux. So the deltas are:

* Maven 3.6.0 (works) - 3.6.3 (fails)
* OS - Mac (works) - Linux (fails)
* JDK 11.0.1 (works) - 11.0.3 (fails)

This is the DSL that I used:
```
#This is a starter DSL to show off some of the features. Make sure you change it to be what you need !.
[when]There is an Instance with field of "{value}"=i: Instance(field=="{value}")
[when]Instance is at least {number} and field is "{value}"=i: Instance(number > {number}, location=="{value}")
[then]Log : "{message}"=System.out.println("{message}");
[then]Set field of instance to "{value}"=i.setField("{value}");
[then]Create instance : "{value}"=insert(new Instance("{value}"));
[when]There is no current Instance with field : "{value}"=not Instance(field == "{value}")
[then]Report error : "{error}"=System.err.println("{error}");
[then]Retract the fact : '{variable}'=retract({variable}); //this would retract bound variable {variable}
```

Also, I tried on 7.37.0 and 7.38.0 on the Mac and it works consistently across both versions. The failure on Linux is on 7.37.0, I will try on 7.38.0 next

**Comment by caponetto** [comment]
Hi @bsbodden. I'm still not able to reproduce this issue.
Does it work if you try to generate the archetype through CLI using the following command?
```
mvn archetype:generate \
  -DarchetypeGroupId=<archetype-groupId> \
  -DarchetypeArtifactId=<archetype-artifactId> \
  -DarchetypeVersion=<archetype-version> \
  -DgroupId=<my.groupid> \
  -DartifactId=<my-artifactId> \
  -B
```

**Comment by bsbodden** [comment]
@caponetto it seems that the issue is somewhere in the Velocity template processing in the Archetype Plugin. Eventually I was getting a Velocity exception on one of the `{` in the DSL. I ended up having to turn off the pre-processing of DSL files as shown below:

```
<?xml version="1.0" encoding="UTF-8"?>
<archetype-descriptor
        xsi:schemaLocation="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-descriptor/1.0.0
        http://maven.apache.org/xsd/archetype-descriptor-1.0.0.xsd"
        xmlns="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-descriptor/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        name="${artifactId}">
  <fileSets>
    <fileSet filtered="true" packaged="false" encoding="UTF-8">
      <directory/>
      <excludes>
        <exclude>**/*.dsl</exclude>
      </excludes>
    </fileSet>
    <fileSet filtered="false" packaged="false" encoding="UTF-8">
      <directory/>
      <includes>
        <include>**/*.dsl</include>
      </includes>
    </fileSet>
  </fileSets>
</archetype-descriptor>
```

There must be something in the combo of Maven/JVM/OS/perhaps the velocity dependency where it does not handle well the `{}` in a DSL.

**Comment by caponetto** [comment]
Thanks for this information, @bsbodden!
